name: Run XSpec Tests

on: [push, pull_request]

jobs:
  xspec-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install Java
      run: |
        sudo apt-get update
        sudo apt-get install -y openjdk-11-jdk

    - name: Install Saxon and XSpec
      run: |
        wget https://repo1.maven.org/maven2/net/sf/saxon/Saxon-HE/10.6/Saxon-HE-10.6.jar -O saxon-he.jar
        git clone https://github.com/xspec/xspec.git
        cd xspec
        ./bin/xspec.sh -h

    - name: Download XSpec file
      run: |
        wget https://github.com/andrewdaylondon/hello_world_py_test/blob/main/hhc_to_taa.xspec -O ../hhc_to_taa.xspec

    - name: Run XSpec tests
      run: |
        cd xspec
        ./bin/xspec.sh ../hhc_to_taa.xspec
